const upComingTableMockData = [
  {
    id: 11,
    contract_address: 'sadasad',
    collection_image: null,
    collection_name: 'sdsfdf',
    quantity: 'sdf',
    presale_price: 'sdfs',
    publicsale_price: 'sdf',
    max_mint: 'sdf',
    publicsale_mint_timestamp: 'sdfsd',
    presale_mint_timestamp: 'sdfs',
    discord_link: 'https://ef51a6.netlify.app/',
    discord_member: 'sdfsdf',
    twitter_link: 'https://ef51a6.netlify.app/',
    twitter_member: 'sdfsdf',
    opensea_link: 'https://ef51a6.netlify.app/',
    os_royalty: 'sdfsdf',
    listing_fee: 'sdfs',
    floor: null,
    nft_royalty: 'sdfsdf',
    hidden: false,
    sortorder: 1,
    access_key: 'sdf',
    enable_access_key: false,
    createdAt: '2022-04-10T18:20:16.000Z',
    updatedAt: '2022-04-10T18:20:16.000Z'
  },
  {
    id: 9,
    contract_address: 'salam',
    collection_image: null,
    collection_name: 'Mutant',
    quantity: '11',
    presale_price: '12 ETH',
    publicsale_price: '11 ETH',
    max_mint: '11',
    publicsale_mint_timestamp: '600000000',
    presale_mint_timestamp: '6000000000',
    discord_link: 'https://recoiljs.org/',
    discord_member: '11k',
    twitter_link: 'https://recoiljs.org/',
    twitter_member: '6k',
    opensea_link: 'https://recoiljs.org/',
    os_royalty: '2.5 %',
    listing_fee: '5 %',
    floor: '500',
    nft_royalty: 'asd',
    hidden: false,
    sortorder: 1,
    access_key: 'asdasd2312321',
    enable_access_key: false,
    createdAt: '2022-04-07T09:45:44.000Z',
    updatedAt: '2022-04-07T10:29:11.000Z'
  },
  {
    id: 7,
    contract_address: 'asdasdasd',
    collection_image: null,
    collection_name: 'Mutant',
    quantity: '11',
    presale_price: '12 ETH',
    publicsale_price: '11 ETH',
    max_mint: '11',
    publicsale_mint_timestamp: '600000000',
    presale_mint_timestamp: '6000000000',
    discord_link: 'https://ef51a6.netlify.app/',
    discord_member: '11k',
    twitter_link: 'https://ef51a6.netlify.app/',
    twitter_member: '6k',
    opensea_link: 'https://ef51a6.netlify.app/',
    os_royalty: '2.5 %',
    listing_fee: '5 %',
    floor: '500',
    nft_royalty: 'asd',
    hidden: false,
    sortorder: 1,
    access_key: '',
    enable_access_key: false,
    createdAt: '2022-04-07T09:45:40.000Z',
    updatedAt: '2022-04-10T18:21:00.000Z'
  }
]
export default upComingTableMockData
