import Head from "next/head";
import HomePage from "./home";

const Home = () => {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <HomePage />
    </>
  );
};

export default Home;
